### ISSUE TITLE
Maths.ahk Line 132: Illegal Character in Expression

### ISSUE THREAD

**Issue by Ruined1** [aviaryan/autohotkey-scripts#2]
autohotkey-scripts/Functions/Maths.ahk
---------------
When compiling a script that #Include, Maths.ahk;

Error at line 132 in #include file "Maths.ahk"

Line Text: {"
Error: The leftmost character above is illegal in an expression.

The program will exit.

**Comment by aviaryan** [comment]
The line contains an array declaration. Make sure you are using AHK version 1.1+ . Download from http://ahkscript.org/

**Comment by Ruined1** [comment]
That fixed it, once I upgraded to the latest version, the issue was resolved. Sorry about that.
