### ISSUE TITLE
Your AhkIni - lib Docs

### ISSUE THREAD

**Issue by IGitSylvia** [aviaryan/autohotkey-scripts#3]
Hi, I am very interested in your Ahkini lib, but currently the link on http://www.autohotkey.com/board/topic/95162-ahkini-fast-ini-lib-with-linked-comments-support for the documentation is down. Would you mind telling me where I can find those docs? 

It would probably be a good idea to update the docs link as well, since the download link to the script does work, which makes people think Ahkini still alive.

:)

**Comment by aviaryan** [comment]
Sorry I changed my site URL so the link became invalid. 
The link is
http://aviaryan.in/ahk/functions/ahkini.html
I have also updated it on the forum.
