### ISSUE TITLE
Sending literal characters with HtmlTag

### ISSUE THREAD

**Issue by iriman** [aviaryan/autohotkey-scripts#5]
Hi, thanks for this useful script.
In case of having characters like curly braces it doesn't work.
https://github.com/aviaryan/autohotkey-scripts/blob/4abad9ef1a53d19cd53157da5692918e1f5f315f/Tools/HtmlTag.ahk#L148
If we add `{RAW}` then it will work:
```
Else SendPlay {RAW} %ToSend%
```

An example for this is the OSM wiki templates like {{LL|$}} in which $ is the delimiter.

**Comment by aviaryan** [comment]
Thanks, that makes sense. 
Would you like to send a PR?

**Comment by iriman** [comment]
#6

**Comment by Monal5031** [comment]
@aviaryan is this issue fixed? :thinking:

**Comment by aviaryan** [comment]
@Monal5031 Yes
